# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: doctor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'doctor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64octor.proto\x12\x06\x64octor\"8\n\rDoctorRequest\x12\x11\n\tspecialty\x18\x01 \x01(\t\x12\x14\n\x0cneighborhood\x18\x02 \x01(\t\"O\n\nDoctorData\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tspecialty\x18\x03 \x01(\t\x12\x14\n\x0cneighborhood\x18\x04 \x01(\t\"1\n\nDoctorList\x12#\n\x07\x64octors\x18\x01 \x03(\x0b\x32\x12.doctor.DoctorData2M\n\x10\x44octorController\x12\x39\n\nGetDoctors\x12\x15.doctor.DoctorRequest\x1a\x12.doctor.DoctorList\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'doctor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOCTORREQUEST']._serialized_start=24
  _globals['_DOCTORREQUEST']._serialized_end=80
  _globals['_DOCTORDATA']._serialized_start=82
  _globals['_DOCTORDATA']._serialized_end=161
  _globals['_DOCTORLIST']._serialized_start=163
  _globals['_DOCTORLIST']._serialized_end=212
  _globals['_DOCTORCONTROLLER']._serialized_start=214
  _globals['_DOCTORCONTROLLER']._serialized_end=291
# @@protoc_insertion_point(module_scope)
